# Generated by Django 5.0.6 on 2024-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('book_cover', models.ImageField(blank=True, default='book_covers/vazio.jpg', null=True, upload_to='book_covers/')),
            ],
        ),
    ]
